# playbooks/show_vlan.yml
- name: Show VLANs on ProCurve
  hosts: all
  gather_facts: no

  tasks:
    - name: Run "show vlan" with an allocated pty
      raw: show vlan
      args:
        pty: yes
      register: vlan_out

    - name: Print VLAN output
      debug:
        var: vlan_out.stdout_lines 
