# playbooks/show_vlan_expect.yml
- name: Show VLANs on ProCurve via expect
  hosts: all
  gather_facts: no

  tasks:
    - name: Prime session and handle press-any-key, then run "show vlan"
      expect:
        command: ssh {{ ansible_user }}@{{ inventory_hostname }} \
                 -o StrictHostKeyChecking=no \
                 "show vlan"
        responses:
          # Intercepts the auto "Press any key to continue" banner
          "Press any key": "\r"
          # After CLI prompt appears, ansible sends the show vlan command
          ".*[#>]": "show vlan\r"
        timeout: 15
      register: vlan_raw

    - name: Display the VLAN information
      debug:
        var: vlan_raw.stdout_lines
