- name: Keep SSH session alive via background shell
  hosts: all
  gather_facts: no
  connection: ssh

  tasks:
    - name: RAWR XD
      comware_command:
        commands:
          -display vlan
      register: vlan_outpust

      name: Display results 
      debug:
        var: vlan_output

