---
- name: Test SSH connection to ProCurve
  hosts: HP Procurve 2910 Switch Puuhanurkka
  gather_facts: no
  connection: network_cli

  vars:
    ansible_network_os: community.network.procurve

  tasks:
    - name: Run 'show vlan'
      ansible.netcommon.cli_command:
        command: show vlan
