---
- name: Show VLANs via raw SSH
  hosts: all
  gather_facts: no
  connection: ssh

  tasks:
    - name: Send dummy newline to clear "Press any key" prompt
      ansible.builtin.raw: "\n"
      register: dummy
      ignore_errors: yes

    - name: Wait a moment for the prompt to be ready
      ansible.builtin.wait_for:
        timeout: 2

    - name: Retry show vlan until successful
      ansible.builtin.raw: "show vlan"
      register: vlan_output
      retries: 3
      delay: 2
      until: vlan_output is succeeded


    - name: Display VLAN output
      debug:
        var: vlan_output.stdout_lines
