- name: Show VLANs via raw SSH
  hosts: all
  gather_facts: no

  tasks:
    - name: Send dummy newline to clear MOTD
      ansible.builtin.raw: "\n"
      register: dummy
      ignore_errors: yes
    
    - name: Wait for banner to finish
      ansible.builtin.wait_for:
        timeout: 2
    
    - name: Run “show vlan”
      ansible.builtin.raw: "show vlan"

