- name: Keep SSH session alive via background shell
  hosts: all
  gather_facts: no
  connection: ssh

  tasks:
    - name: Start background shell to keep session open
      raw: "nohup /bin/sh >/dev/null 2>&1 &"
      ignore_errors: yes

    - name: Run show vlan via expect
      expect:
        command: ssh {{ ansible_user }}@{{ inventory_hostname }} "show vlan"
        responses:
          "Press any key": "\r"
          ".*[#>]": "show vlan\r"
        timeout: 15
      register: vlan_result

    - name: Display VLAN output
      debug:
        var: vlan_result.stdout_lines
