- name: Keep SSH session alive via background shell
  hosts: all
  gather_facts: no
  connection: ssh

  tasks:
    - name: Start background shell to keep session open
      raw: "\r"
      raw: "show vlan"
      register: vlan_result

    - name: Display VLAN output
      debug:
        var: vlan_result.stdout_lines
