---
- name: Show VLANs using expect on ProCurve switch
  hosts: all
  gather_facts: no
  vars:
    ansible_connection: ssh

  tasks:
    - name: Send "show vlan" with expect
      ansible.builtin.expect:
        command: ssh -o StrictHostKeyChecking=no {{ inventory_hostname }}
        responses:
          'Press any key to continue': "\r"
          '.*[>#]': "show vlan\r"
        timeout: 10
      register: output

    - name: Show VLAN output
      debug:
        var: output.stdout_lines
