- name: Show VLANs via raw SSH
  hosts: all
  gather_facts: no

  tasks:
    - name: Run “show vlan”
      raw: show vlan
      register: vlan_out

    - name: Display VLANs
      debug:
        var: vlan_out.stdout_lines 
