- name: Run Netmiko logic via inline Python
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Connect to ProCurve switch and run show version
      community.general.run_python:
        code: |
          from netmiko import ConnectHandler
          device = {
              "device_type": "hp_procurve",
              "ip": "172.30.133.155",
              "username": "admin",
              "password": "yourpassword",
          }
          net_connect = ConnectHandler(**device)
          output = net_connect.send_command("show version")
          print(output)
          net_connect.disconnect()
