# playbooks/show_vlan_expect.yml
- name: Show VLANs on ProCurve via expect
  hosts: all
  gather_facts: no

  tasks:
    - name: SSH in, run show vlan, exit
      ansible.builtin.expect:
        command: ssh admin@{{ inventory_hostname }}
        responses:
          'assword:': "{{ ansible_password }}"
          '^[^#]+#$': |
            show vlan
            exit
        timeout: 30
      register: vlan_session

    - name: Display VLAN output
      debug:
        var: vlan_session.stdout_lines 
