---
- name: Test HP ProCurve Connection and Create VLAN
  hosts: all
  gather_facts: no
  connection: ssh

  tasks:
    - name: Show Vlan #first raw clears press any key to continue
      raw: k
      raw: show vlan
      register: vlan_o
        
    - name: output
      debug:
        var: vlan_o.stdout
