---
- name: Show VLANs via raw SSH
  hosts: all
  gather_facts: no

  tasks:
    - name: Wait for banner to finish
      ansible.builtin.wait_for:
        timeout: 2

    - name: Run show vlan
      ansible.builtin.raw: "show vlan"
      register: vlan_output

    - name: Show VLAN output
      debug:
        var: vlan_output.stdout
