---
- name: Test HP ProCurve Connection and Create VLAN
  hosts: all
  gather_facts: no
  connection: ssh

  tasks:
    - name: Show Vlan #first raw clears press any key to continue
      raw: k
      raw: configure
      raw: vlan 100
      raw: name "AWX TEST"
      raw: exit  
      raw: exit
      raw: write memory
      raw: exit
      raw: exit
      raw: y
