---
- name: Test HP ProCurve Connection and Create VLAN
  hosts: procurve-2910
  gather_facts: no
  connection: network_cli

  tasks:
    - name: Create VLAN 100 with name TestVLAN
      community.network.procurve_vlan:
        vlan_id: 100
        name: TestVLAN
        state: present