- name: HP ProCurve Commands
  hosts: all
  gather_facts: no
  vars:
    ansible_connection: network_cli
    ansible_command_timeout: 30
  
  tasks:
    - name: Execute show vlan
      ansible.netcommon.cli_command:
        command: show vlan
      register: vlan_info
      
    - debug:
        var: vlan_info.stdout
